import { createClient } from '../../../lib/supabase/server'
import { MediaUploader } from '../../components/media-uploader'
import { MediaMetadataForm } from '../../components/media-metadata-form'
import { AdminDeleteButton } from '../../components/admin-delete-button'

export default async function MediaPage() {
  const supabase = await createClient(); const { data, error } = await supabase.from('media_assets').select('id,filename,mime_type,size_bytes,alt_text,is_decorative,created_at').order('created_at', { ascending: false })
  return <main className="min-h-screen bg-[#f3f0ea] p-6 text-[#171717] md:p-10"><a href="/admin" className="text-xs text-black/50">← Back to overview</a><div className="mt-10"><p className="mono text-[10px] text-[#b36f43]">LOGIKAin / MEDIA</p><h1 className="mt-3 text-4xl font-extrabold tracking-[-2px]">Media library</h1><p className="mt-2 text-sm text-black/50">Upload, edit metadata, and delete unused assets.</p></div><div className="mt-10"><MediaUploader /></div><div className="mt-5 overflow-x-auto border border-black/10 bg-white/50">{error ? <p className="p-6 text-sm text-red-700">Media table belum tersedia.</p> : <table className="w-full min-w-[980px] text-left text-xs"><thead className="border-b border-black/10 bg-black/5"><tr>{['filename','type','size','metadata','actions'].map((column) => <th key={column} className="px-5 py-4 font-bold uppercase tracking-wider text-black/50">{column}</th>)}</tr></thead><tbody>{(data || []).map((asset) => <tr key={asset.id} className="border-b border-black/10"><td className="px-5 py-4 font-bold">{asset.filename}</td><td className="px-5 py-4">{asset.mime_type || '—'}</td><td className="px-5 py-4">{asset.size_bytes ? `${Math.ceil(asset.size_bytes / 1024)} KB` : '—'}</td><td className="px-5 py-4"><MediaMetadataForm id={asset.id} altText={asset.alt_text} decorative={asset.is_decorative} /></td><td className="px-5 py-4"><AdminDeleteButton id={asset.id} kind="media" /></td></tr>)}</tbody></table>}</div></main>
}
