'use client'

import { useState, useTransition } from 'react'
import { createClientRecord, deleteClientRecord, updateClientRecord } from '../actions/admin'

type Client = { id?: string; name: string; legal_name?: string | null; email?: string | null; phone?: string | null; status: string }
const input = 'border border-black/15 bg-transparent px-3 py-2 text-xs'

export function ClientCrudForm({ client }: { client?: Client }) {
  const [pending, startTransition] = useTransition(); const [message, setMessage] = useState('')
  return <div className="border border-black/10 bg-white/50 p-4"><form className="grid gap-2 md:grid-cols-[1fr_1fr_1.2fr_1fr_1fr_auto]" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const payload = { id: client?.id, name: form.get('name'), legal_name: form.get('legal_name'), email: form.get('email'), phone: form.get('phone'), status: form.get('status') }; setMessage(''); startTransition(async () => { try { if (client) await updateClientRecord(payload); else await createClientRecord(payload); setMessage(client ? 'Updated' : 'Created'); if (!client) event.currentTarget.reset() } catch (error) { setMessage(error instanceof Error ? error.message : 'Save failed') } }) }}><input required name="name" defaultValue={client?.name} placeholder="Client name" className={input} /><input name="legal_name" defaultValue={client?.legal_name || ''} placeholder="Legal name" className={input} /><input type="email" name="email" defaultValue={client?.email || ''} placeholder="Email" className={input} /><input name="phone" defaultValue={client?.phone || ''} placeholder="Phone" className={input} /><select name="status" defaultValue={client?.status || 'prospect'} className={`${input} bg-[#f3f0ea]`}><option value="prospect">Prospect</option><option value="active">Active</option><option value="inactive">Inactive</option><option value="archived">Archived</option></select><button disabled={pending} className="bg-[#171717] px-3 py-2 text-[10px] font-bold text-[#f3f0ea]">{pending ? '...' : client ? 'Save' : '+ Create'}</button>{message && <span className="text-[10px] text-[#b36f43] md:col-span-6">{message}</span>}</form>{client && <div className="mt-2"><button disabled={pending} onClick={() => { if (window.confirm('Hapus client ini?')) startTransition(async () => { try { await deleteClientRecord(client.id!) } catch (error) { setMessage(error instanceof Error ? error.message : 'Delete failed') } }) }} className="text-[10px] font-bold text-red-700">Delete client</button></div>}</div>
}
