'use client'

import { useState, useTransition } from 'react'
import { createInvoice, createQuote, recordPayment } from '../actions/admin'

export function FinanceForm({ type }: { type: 'quote' | 'invoice' | 'payment' }) {
  const [open, setOpen] = useState(false); const [pending, startTransition] = useTransition(); const [message, setMessage] = useState('')
  return <div className="border border-black/10 bg-white/50 p-5"><button onClick={() => setOpen(!open)} className="text-xs font-bold text-[#b36f43]">{open ? '− Close' : `+ New ${type}`}</button>{open && <form className="mt-4 grid gap-3 sm:grid-cols-2" onSubmit={(event) => { event.preventDefault(); const raw = Object.fromEntries(new FormData(event.currentTarget)); startTransition(async () => { try { if (type === 'quote') await createQuote({ ...raw, total_minor: Number(raw.total_minor) }); else if (type === 'invoice') await createInvoice({ ...raw, total_minor: Number(raw.total_minor) }); else await recordPayment({ ...raw, amount_minor: Number(raw.amount_minor) }); setMessage('Saved.'); (event.currentTarget as HTMLFormElement).reset() } catch { setMessage('Could not save record.') } }) }}><input required name={type === 'payment' ? 'invoice_id' : type === 'quote' ? 'quote_number' : 'invoice_number'} placeholder={type === 'payment' ? 'Invoice ID' : `${type} number`} className="border border-black/15 bg-transparent px-3 py-3 text-xs" />{type !== 'payment' && <input required name="client_id" placeholder="Client ID" className="border border-black/15 bg-transparent px-3 py-3 text-xs" />}{type === 'quote' && <input name="lead_id" placeholder="Lead ID (optional)" className="border border-black/15 bg-transparent px-3 py-3 text-xs" />}{type === 'invoice' && <input name="project_id" placeholder="Project ID (optional)" className="border border-black/15 bg-transparent px-3 py-3 text-xs" />}<input required type="number" min="0" name={type === 'payment' ? 'amount_minor' : 'total_minor'} placeholder="Amount in minor units" className="border border-black/15 bg-transparent px-3 py-3 text-xs" />{type === 'invoice' ? <><input name="issued_at" type="date" aria-label="Issue date" className="border border-black/15 bg-transparent px-3 py-3 text-xs" /><input name="due_at" type="date" aria-label="Due date" className="border border-black/15 bg-transparent px-3 py-3 text-xs" /></> : <input name="valid_until" type="date" className="border border-black/15 bg-transparent px-3 py-3 text-xs" />}<button disabled={pending} className="w-fit bg-[#171717] px-4 py-3 text-xs font-bold text-[#f3f0ea]">{pending ? 'Saving...' : 'Save'}</button>{message && <p className="text-xs text-[#b36f43] sm:col-span-2">{message}</p>}</form>}</div>
}
