'use client'

import { useState, useTransition } from 'react'
import { saveService } from '../actions/admin'

type Service = { id?: string; name?: string; slug?: string; summary?: string; body?: string; status?: string; seo_title?: string; seo_description?: string }

export function ServiceEditor({ service = {} }: { service?: Service }) {
  const [pending, startTransition] = useTransition(); const [message, setMessage] = useState('')
  return <form className="grid max-w-3xl gap-4" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); setMessage(''); startTransition(async () => { try { await saveService({ id: service.id, name: form.get('name'), slug: form.get('slug'), summary: form.get('summary'), body: form.get('body'), status: form.get('status'), seo_title: form.get('seo_title'), seo_description: form.get('seo_description') }); setMessage('Saved successfully.') } catch { setMessage('Could not save content.') } }) }}><label className="grid gap-2 text-xs font-bold">Name<input required name="name" defaultValue={service.name} className="border border-black/15 bg-transparent px-4 py-3 text-sm font-normal" /></label><label className="grid gap-2 text-xs font-bold">Slug<input required name="slug" pattern="[a-z0-9-]+" defaultValue={service.slug} className="border border-black/15 bg-transparent px-4 py-3 text-sm font-normal" /></label><label className="grid gap-2 text-xs font-bold">Summary<textarea required name="summary" defaultValue={service.summary} rows={3} className="border border-black/15 bg-transparent px-4 py-3 text-sm font-normal" /></label><label className="grid gap-2 text-xs font-bold">Body<textarea required name="body" defaultValue={service.body} rows={8} className="border border-black/15 bg-transparent px-4 py-3 text-sm font-normal" /></label><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-xs font-bold">Status<select name="status" defaultValue={service.status || 'draft'} className="border border-black/15 bg-[#f3f0ea] px-4 py-3 text-sm font-normal"><option value="draft">Draft</option><option value="review">Review</option><option value="published">Published</option><option value="archived">Archived</option></select></label><label className="grid gap-2 text-xs font-bold">SEO title<input name="seo_title" defaultValue={service.seo_title} className="border border-black/15 bg-transparent px-4 py-3 text-sm font-normal" /></label></div><label className="grid gap-2 text-xs font-bold">SEO description<textarea name="seo_description" defaultValue={service.seo_description} rows={3} className="border border-black/15 bg-transparent px-4 py-3 text-sm font-normal" /></label><button disabled={pending} className="w-fit bg-[#171717] px-5 py-4 text-xs font-bold text-[#f3f0ea]">{pending ? 'Saving...' : 'Save content'}</button>{message && <p className="text-xs text-[#b36f43]">{message}</p>}</form>
}
