import Link from 'next/link'
import { BusinessDiagnostic } from './components/business-diagnostic'
import { ContactForm } from './components/contact-form'
import { Nav } from './components/nav'
import { Footer } from './components/footer'
import { getIndustries, getInsights, getProjects, getServices, getTestimonials } from '../lib/content-repository'

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://logikain.id'

export default async function Home() {
  const [services, projects, industries, insights, testimonials] = await Promise.all([getServices(), getProjects(), getIndustries(), getInsights(), getTestimonials()])
  const jsonLd = { '@context': 'https://schema.org', '@type': 'Organization', name: 'LOGIKAin', url: siteUrl, description: 'Partner digital untuk merapikan proses, membangun produk, dan mengotomatisasi bisnis.', email: 'hello@logikain.id' }
  return <>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
    <Nav />
    <main>
      <section className="section-pad grid min-h-[680px] items-center gap-12 py-16 md:grid-cols-[1.05fr_.95fr] md:py-20">
        <div><p className="mono text-[10px] text-muted"><i className="mr-2 inline-block h-1.5 w-1.5 rounded-full bg-orange" /> DIGITAL PARTNER UNTUK BISNIS YANG BERGERAK</p><h1 className="display mt-7 max-w-4xl text-5xl font-extrabold md:text-[clamp(64px,7vw,104px)]">Yang rumit,<br /><em className="not-italic text-orange">kami LOGIKAin.</em></h1><p className="mt-8 max-w-xl text-base leading-8 text-muted">Kami merapikan proses, membangun produk digital, dan mengotomatisasi pekerjaan berulang—supaya tim Anda bisa bekerja lebih jelas dan bisnis bergerak lebih cepat.</p><div className="mt-9 flex flex-wrap gap-4"><Link href="/start-project" className="bg-ink px-5 py-4 text-xs font-bold text-paper hover:bg-orange">Ceritakan tantangan Anda <span className="ml-2">↗</span></Link><Link href="/services" className="border-b border-ink pb-2 text-xs font-bold hover:text-orange">Lihat solusi <span className="ml-2">↓</span></Link></div><div className="mt-12 grid max-w-xl grid-cols-3 gap-4 border-t border-line pt-5 text-xs"><span><b className="block text-xl">01</b><span className="text-muted">Understand</span></span><span><b className="block text-xl">02</b><span className="text-muted">Build</span></span><span><b className="block text-xl">03</b><span className="text-muted">Improve</span></span></div></div>
        <div className="relative flex min-h-[420px] items-center justify-center overflow-hidden bg-[#e9e1d6] p-8 md:min-h-[560px]"><div className="absolute -right-16 -top-16 h-64 w-64 rounded-full border border-orange/30" /><div className="relative text-center"><p className="text-5xl font-extrabold tracking-[-4px] md:text-8xl">LOGIKA<span className="text-orange">in</span></p><p className="mono mt-4 text-[10px] text-muted">THINK CLEARLY. BUILD LOGICALLY.</p></div><p className="absolute bottom-7 right-7 max-w-[180px] text-right text-xs leading-5 text-muted">Dari kompleksitas menjadi kejelasan yang bisa dipakai.</p></div>
      </section>
      <div className="overflow-hidden whitespace-nowrap border-y border-line py-4"><div className="ticker-track mono text-[11px] tracking-[2px] text-muted">STRATEGY <span className="mx-6 text-orange">✳</span> SYSTEM <span className="mx-6 text-orange">✳</span> AUTOMATION <span className="mx-6 text-orange">✳</span> PRODUCT <span className="mx-6 text-orange">✳</span> CLARITY <span className="mx-6 text-orange">✳</span> STRATEGY <span className="mx-6 text-orange">✳</span> SYSTEM</div></div>
      <section id="services" className="section-pad scroll-mt-24 py-24 md:py-32"><div className="grid gap-8 md:grid-cols-[.7fr_1.3fr]"><p className="mono text-[10px] text-muted">01 / SOLUSI</p><div><h2 className="display max-w-4xl text-4xl font-extrabold md:text-6xl">Teknologi yang<br /><em className="not-italic text-orange">menyelesaikan masalah nyata.</em></h2><p className="mt-6 max-w-xl leading-7 text-muted">Tidak semua masalah membutuhkan aplikasi baru. Kami mulai dari konteks, lalu memilih sistem yang benar-benar membantu kerja sehari-hari.</p></div></div><div className="mt-14 grid gap-3 md:grid-cols-3">{services.slice(0, 6).map((service, i) => <Link href={`/services/${service.slug}`} key={service.slug} className="group flex min-h-64 flex-col border border-line p-6 transition hover:-translate-y-1 hover:border-orange"><span className="mono text-[10px] text-orange">0{i + 1}</span><h3 className="mt-14 text-2xl font-extrabold tracking-[-1px] group-hover:text-orange">{service.name}</h3><p className="mt-3 text-sm leading-6 text-muted">{service.summary}</p><span className="mt-auto pt-8 text-xs font-bold">Pelajari solusi <span className="text-orange">↗</span></span></Link>)}</div></section>
      <section id="work" className="section-pad scroll-mt-24 bg-ink py-24 text-paper md:py-32"><div className="grid gap-8 md:grid-cols-[.7fr_1.3fr]"><p className="mono text-[10px] text-orange">02 / PROOF OF WORK</p><div><h2 className="display max-w-4xl text-4xl font-extrabold md:text-6xl">Dampak yang terasa<br /><em className="not-italic text-orange">di pekerjaan sehari-hari.</em></h2><div className="mt-12 grid gap-3 md:grid-cols-3">{projects.slice(0, 3).map((project, i) => <Link href={`/projects/${project.slug}`} key={project.slug} className="border border-white/15 p-5 transition hover:border-orange"><span className="mono text-[10px] text-orange">0{i + 1}</span><h3 className="mt-14 text-xl font-bold">{project.name}</h3><p className="mt-3 text-xs leading-6 text-paper/60">{project.summary}</p></Link>)}</div></div></div></section>
      <section id="industries" className="section-pad scroll-mt-24 py-24 md:py-32"><div className="grid gap-8 md:grid-cols-[.7fr_1.3fr]"><p className="mono text-[10px] text-muted">03 / KONTEKS</p><div><h2 className="display text-4xl font-extrabold md:text-6xl">Solusi yang mengikuti<br /><em className="not-italic text-orange">dunia bisnis Anda.</em></h2><div className="mt-12 grid gap-3 sm:grid-cols-2">{industries.map((industry) => <Link href={`/industries/${industry.slug}`} key={industry.slug} className="border-t border-line py-5 text-lg font-bold hover:text-orange">{industry.name}<span className="float-right text-orange">↗</span><small className="mt-2 block text-xs font-normal leading-6 text-muted">{industry.summary}</small></Link>)}</div></div></div></section>
      <section id="process" className="section-pad scroll-mt-24 border-y border-line bg-[#e9e1d6] py-24 md:py-32"><div className="grid gap-8 md:grid-cols-[.7fr_1.3fr]"><p className="mono text-[10px] text-muted">04 / CARA KERJA</p><div><h2 className="display text-4xl font-extrabold md:text-6xl">Dengar. Rancang.<br /><em className="not-italic text-orange">Gerakkan.</em></h2><div className="mt-12 border-t border-line">{[['01','Dengar & pahami','Kami masuk ke konteks bisnis sebelum menawarkan solusi.'],['02','Rancang yang relevan','Kami menentukan prioritas yang bisa dipakai dan diukur.'],['03','Bangun & bertumbuh','Solusi diluncurkan, dipelajari, lalu dikembangkan bersama tim.']].map(([number, title, text]) => <div key={number} className="grid gap-3 border-b border-line py-6 md:grid-cols-[70px_1fr_1fr]"><span className="mono text-[11px] text-orange">{number}</span><b>{title}</b><p className="text-sm leading-6 text-muted">{text}</p></div>)}</div></div></div></section>
      <section id="insights" className="section-pad scroll-mt-24 py-24 md:py-32"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="mono text-[10px] text-muted">05 / INSIGHT</p><h2 className="display mt-4 text-4xl font-extrabold md:text-6xl">Cara berpikir<br /><em className="not-italic text-orange">yang bisa dibagikan.</em></h2></div><Link href="/insights" className="text-xs font-bold">Lihat semua insight ↗</Link></div><div className="mt-12 grid gap-3 md:grid-cols-3">{insights.slice(0, 3).map((insight) => <Link href={`/insights/${insight.slug}`} key={insight.slug} className="border border-line p-6 hover:border-orange"><p className="mono text-[10px] text-orange">INSIGHT</p><h3 className="mt-14 text-xl font-bold">{insight.name}</h3><p className="mt-3 text-sm leading-6 text-muted">{insight.summary}</p></Link>)}</div></section>
      {testimonials.length > 0 && <section className="section-pad bg-[#d8c8b7] py-20"><div className="grid gap-3 md:grid-cols-3">{testimonials.map((item) => <figure key={`${item.author_name}-${item.quote}`} className="border border-ink/15 p-6"><blockquote className="text-lg font-bold leading-7">“{item.quote}”</blockquote><figcaption className="mt-6 text-xs text-muted">{item.author_name}{item.company_name ? ` · ${item.company_name}` : ''}</figcaption></figure>)}</div></section>}
      <section className="section-pad grid gap-10 bg-[#efe8df] py-24 md:grid-cols-[.9fr_1.1fr] md:py-32"><div><p className="mono text-[10px] text-muted">06 / PRIORITAS</p><h2 className="display mt-5 text-4xl font-extrabold md:text-6xl">Mulai dari<br /><em className="not-italic text-orange">yang paling penting.</em></h2><p className="mt-6 max-w-md text-sm leading-7 text-muted">Jawab dua pertanyaan singkat untuk mendapatkan arah awal sebelum memulai percakapan.</p></div><BusinessDiagnostic /></section>
    </main>
    <Footer />
  </>
}
